apiVersion: v1
kind: Secret
metadata:
  name: harvest-backend-secrets
  namespace: harvest-mood
type: Opaque
stringData:
  db-password: "H@rv3stP@ss!"  # stringData автоматично закодує в base64
  jwt-secret: "secret"