apiVersion: v1
kind: Service
metadata:
  name: harvest-backend-service
  namespace: harvest-mood
spec:
  selector:
    app: harvest-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP